name: GitHub Actions Test
run-name: ${{ github.actor }} workflow test
on: [push]
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi! I'm running because of a ${{ github.event_name }} event."
      - run: echo "Checking out the repository from ${{ github.repository }}."
      - name: Clone repository code
        uses: actions/checkout@v4
      - run: echo "Repository cloned, I think I'm ready. The files look like this:"
      - name: List files
        run: 
          ls ${{github.workspace }}
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Install Azure ML CLI Extension
        run: |
          az extension add -n ml -y
          az extension update -n ml
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.HUMANACTIVITYRECOGNITION_CREDENTIALS }}'
      - name: Test azure login by getting details
        run: az account show
      - name: Submit Azure ML Job
        run: az ml job create --file job.yaml --resource-group CW2-Com774-B00910932 --workspace-name CW2-ML-Workspace
